version: "3"

services:
  namenode:
    image: harbor.software.dc/mpdata/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
      - "8020:8020"
  datanode:
    image: harbor.software.dc/mpdata/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50010:50010"
      - "50020:50020"
      - "50075:50075"
  resourcemanager:
    image: harbor.software.dc/mpdata/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop-hive.env
    ports:
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8088:8088"

  nodemanager1:
    image: harbor.software.dc/mpdata/hadoop-nodemanager:2.0.0-hadoop2.7.4-java8
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop-hive.env
    ports:
      - "8042:8042"
  
  historyserver:
    image: harbor.software.dc/mpdata/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
    container_name: historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop-hive.env
    ports:
      - "8188:8188"
      - "10020:10020"

  hive-server:
    image: harbor.software.dc/mpdata/hive:1.2.1-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
      ATLAS_HOOK: "false" 
    ports:
      - "10000:10000"
  hive-metastore:
    image: harbor.software.dc/mpdata/hive:1.2.1-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    image: harbor.software.dc/mpdata/hive-metastore-postgresql:1.2.0
    ports:
      - "5432:5432"
  presto-coordinator:
    image: harbor.software.dc/mpdata/prestodb:0.183
    ports:
      - "8080:8080"

volumes:
  namenode:
  datanode:
  hadoop_historyserver:

networks:
  default:
    external:
      name: hadoop-ljzt
