version: "3"

services:
  namenode:
    image: harbor.software.dc/mpdata/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    hostname: namenode
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
      - "8020:8020"
  datanode:
    image: harbor.software.dc/mpdata/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    hostname: datanode
    ports:
      - "50010:50010"
      - "50020:50020"
      - "50075:50075"
    depends_on:
      - "namenode"
  resourcemanager:
    image: harbor.software.dc/mpdata/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop-hive.env
    hostname: resourcemanager
    ports:
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8088:8088"
    depends_on:
      - "namenode"
      - "datanode"
  nodemanager:
    image: harbor.software.dc/mpdata/hadoop-nodemanager:2.0.0-hadoop2.7.4-java8
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    hostname: nodemanager
    env_file:
      - ./hadoop-hive.env
    ports:
      - "8040:8040"
      - "8041:8041"
      - "8042:8042"
      - "50031-50040:50031-50040"
    depends_on:
      - "namenode"
      - "datanode"
      - "resourcemanager"
  historyserver:
    image: harbor.software.dc/mpdata/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
    container_name: historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop-hive.env
    hostname: historyserver
    ports:
      - "8188:8188"
      - "10200:10200"
      - "10020:10020"
      - "19888:19888"
    depends_on:
      - "namenode"
      - "datanode"
      - "resourcemanager"

  hive-server:
    image: harbor.software.dc/mpdata/hive:1.2.1-mysql-metastore
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:mysql://hive-metastore-mysql:3306/hive?useSSL=false"
      HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName: "com.mysql.jdbc.Driver"
      HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName: "root"
      HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword: "123456"
      ATLAS_HOOK: "false" 
    hostname: hive-server
    volumes:
      - ./conf/atlas-application.properties:/opt/hive/conf/atlas-application.properties
    ports:
      - "10000:10000"
      - "10002:10002"
    depends_on:
      - "hive-metastore-mysql"
  hive-metastore:
    image: harbor.software.dc/mpdata/hive:1.2.1-mysql-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-mysql:3306"
    ports:
      - "9083:9083"
    depends_on:
      - "namenode"
      - "datanode"
      - "hive-metastore-mysql"
  hive-metastore-mysql:
    image: harbor.software.dc/mysql/mysql:5.7
    restart: always
    container_name: hive-metastore-mysql
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./data/mysql/data:/var/lib/mysql/
      - ./data/mysql/init-sql:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    hostname: hive-metastore-mysql
  presto-coordinator:
    image: harbor.software.dc/mpdata/prestodb:0.183
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - "hive-server"   

volumes:
  namenode:
  datanode:
  hadoop_historyserver:

