version: "3"

services:
  namenode:
    image: harbor.software.dc/mpdata/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    hostname: namenode
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
      - "8020:8020"
  datanode:
    image: harbor.software.dc/mpdata/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    hostname: datanode
    ports:
      - "50010:50010"
      - "50020:50020"
      - "50075:50075"
    depends_on:
      - "namenode"
  resourcemanager:
    image: harbor.software.dc/mpdata/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop-hive.env
    hostname: resourcemanager
    ports:
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8088:8088"
    depends_on:
      - "namenode"
      - "datanode"
  nodemanager:
    image: harbor.software.dc/mpdata/hadoop-nodemanager:2.0.0-hadoop2.7.4-java8
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    hostname: nodemanager
    env_file:
      - ./hadoop-hive.env
    ports:
      - "8040:8040"
      - "8041:8041"
      - "8042:8042"
    depends_on:
      - "namenode"
      - "datanode"
      - "resourcemanager"
  historyserver:
    image: harbor.software.dc/mpdata/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
    container_name: historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop-hive.env
    hostname: historyserver
    ports:
      - "8188:8188"
      - "8189:8189"
      - "10020:10020"
    depends_on:
      - "namenode"
      - "datanode"
      - "resourcemanager"

  hive-server:
    image: harbor.software.dc/mpdata/hive:1.2.1-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
      ATLAS_HOOK: "false" 
    hostname: hive-server
    volumes:
      - ./conf/atlas-application.properties:/opt/hive/conf/atlas-application.properties
    ports:
      - "10000:10000"
      - "10002:10002"
    depends_on:
      - "hive-metastore"
  hive-metastore:
    image: harbor.software.dc/mpdata/hive:1.2.1-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    depends_on:
      - "namenode"
      - "datanode"
      - "hive-metastore-postgresql"

  hive-metastore-postgresql:
    image: harbor.software.dc/mpdata/hive-metastore-postgresql:1.2.0
    ports:
      - "5432:5432"
  presto-coordinator:
    image: harbor.software.dc/mpdata/prestodb:0.183
    ports:
      - "8080:8080"
    depends_on:
      - "hive-server"   

volumes:
  namenode:
  datanode:
  hadoop_historyserver:

networks:
  default:
    external:
      name: hadoop-ljzt
